# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1625dcdf009ef872259e9553efc68400786dba84455f7104bbd7881b90c90a03029e2ffcf02bc2ae1fd3f0eb19bf3487f87787458dd52085389ad7bb9ff9ee49

test:
  secret_key_base: 0f2a6f417369f4d2d011ae2ca3be32b4a00f205bd3439b9241d0a54d888e8f97c96d411ed069364cea57536c3969f2ab3590d88dece07cfa18b199e834999997

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
